sudo: false
language: clojure
lein: 2.9.1
services:
  docker
script:
  - docker-compose up -d
  - lein do clean, all test, all check
jdk:
  - oraclejdk8
  - oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
